### ISSUE TITLE
Demande - aide à la population des classes d\'écoles du dimanche

### ISSUE THREAD

**Issue by EcclesiaCRMBugReport** [phili67/ecclesiacrm#101]
Se serait interessant de définir les âges avec potentiellement la gestion des mois de naissance pour coller au découpage scolaire 

Cela permettrai de proposer automatiquement la bonne classe pour les enfants et gérer les passages de classes d'une année à l'autre 

Collected Value Title |  Data 
----------------------|----------------
Page Name |/sundayschool/SundaySchoolClassView.php
Screen Size |900x1440
Window Size |769x1440
Page Size |1229x1440
Platform Information | Linux tournevis.o2switch.net 3.10.0-714.10.2.lve1.4.79.el6h.x86_64 #1 SMP Thu Jan 4 14:26:00 EST 2018 x86_64
PHP Version | 7.0.26
SQL Version | 10.0.33-MariaDB
EcclesiaCRM Version |3.0.0
Reporting Browser |Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/604.4.7 (KHTML, like Gecko) Version/11.0.2 Safari/604.4.7
Prerequisite Status |All Prerequisites met
Integrity check status |{"status":"success"}
Apache Modules    |mod_rewrite,mod_mime,mod_headers,mod_expires,mod_auth_basic

**Comment by phili67** [comment]
C'est déjà présent dans EcclesiaCRM, je l'avais traité pour la fin depuis la version 2.8.15.
Il faut aller dans le menu requêtes :
![capture d ecran 2018-01-11 a 08 59 12](https://user-images.githubusercontent.com/20263693/34814402-c1bf2f3a-f6ad-11e7-95ea-668484d8786a.png)

Puis on les ajoutes au panier et on peut les affecter à un groupe :
![capture d ecran 2018-01-11 a 09 00 16](https://user-images.githubusercontent.com/20263693/34814439-ed01c4e6-f6ad-11e7-853d-fe1fe0d2d8cb.png)

Puis on peut finalement les mettre dans le panier :
![capture d ecran 2018-01-11 a 09 00 26](https://user-images.githubusercontent.com/20263693/34814458-000f5b5c-f6ae-11e7-8d6e-4cb7a7850c2b.png)

On peut ensuite les affecter à un groupe :
![capture d ecran 2018-01-11 a 09 00 34](https://user-images.githubusercontent.com/20263693/34814463-0470a264-f6ae-11e7-8468-be4e85ac3286.png)
