### ISSUE TITLE
Evolution - Suivi de la fréquentation des groupes

### ISSUE THREAD

**Issue by EcclesiaCRMBugReport** [phili67/ecclesiacrm#106]
Décliner la saisie de la participation avec somme automatique 

Saisie Nombre adultes
Saisie Nombre enfants 
Sommes automatique (Nombre adultes + Nombre enfants )

Bonus : Champs personnalisés  
nombre de visiteur
nombre de personnes ayant répondu à l'appel 
ajout de pj

Collected Value Title |  Data 
----------------------|----------------
Page Name |/EventEditor.php
Screen Size |900x1440
Window Size |769x1440
Page Size |1262x1440
Platform Information | Linux tournevis.o2switch.net 3.10.0-714.10.2.lve1.4.79.el6h.x86_64 #1 SMP Thu Jan 4 14:26:00 EST 2018 x86_64
PHP Version | 7.0.26
SQL Version | 10.0.33-MariaDB
EcclesiaCRM Version |3.0.0
Reporting Browser |Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/604.4.7 (KHTML, like Gecko) Version/11.0.2 Safari/604.4.7
Prerequisite Status |All Prerequisites met
Integrity check status |{"status":"success"}
Apache Modules    |mod_rewrite,mod_mime,mod_headers,mod_expires,mod_auth_basic

**Comment by phili67** [comment]
Je ne comprend pas la demande ?
