### ISSUE TITLE
Uplaod photo personne - Homothétie

### ISSUE THREAD

**Issue by EcclesiaCRMBugReport** [phili67/ecclesiacrm#1316]
L'affichage des photos ne respectent pas l'homothétie cela déforme beaucoup l'aspect de la personne

Test avec photo 890 × 879
De même les photos 240*303 passent aussi très mal 

Collected Value Title |  Data 
----------------------|----------------
Page Name |/PersonView.php
Screen Size |1080x1920
Window Size |751x1425
Page Size |1101x1425
Platform Information | Linux chaise.o2switch.net 3.10.0-714.10.2.lve1.5.17.1.el7.x86_64 #1 SMP Tue May 22 10:39:25 EDT 2018 x86_64
PHP Version | 7.2.19
SQL Version | 10.3.15-MariaDB
EcclesiaCRM Version |5.8.1
Reporting Browser |Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36
Prerequisite Status |All Prerequisites met
Integrity check status |{"status":"success"}
Apache Modules    |mod_rewrite,mod_mime,mod_headers,mod_expires,mod_auth_basic

**Comment by phili67** [comment]
Le bug est résolu
