### ISSUE TITLE
message d\'erreur aléatoire

### ISSUE THREAD

**Issue by EcclesiaCRMBugReport** [phili67/ecclesiacrm#1318]
Disparait au rechargement de la page 

Fatal error: Uncaught Error: Call to undefined method EcclesiaCRM\dto\SystemConfig::isInitialized() in /home/fesy4890/sites/ek/EcclesiaCRM/Bootstrapper.php:175 Stack trace: #0 /home/fesy4890/sites/ek/EcclesiaCRM/Bootstrapper.php(152): EcclesiaCRM\Bootstrapper::testMYSQLI() #1 /home/fesy4890/sites/ek/EcclesiaCRM/Bootstrapper.php(71): EcclesiaCRM\Bootstrapper::initMySQLI() #2 /home/fesy4890/sites/ek/Include/LoadConfigs.php(33): EcclesiaCRM\Bootstrapper::init('localhost', '3306', 'fesy4890_ekuser', 'Ekqskdk98NNds76...', 'fesy4890_ek', '', false, Array, false) #3 /home/fesy4890/sites/ek/Include/Config.php(62): require_once('/home/fesy4890/...') #4 /home/fesy4890/sites/ek/Menu.php(18): require('/home/fesy4890/...') #5 {main} thrown in /home/fesy4890/sites/ek/EcclesiaCRM/Bootstrapper.php on line 175

Collected Value Title |  Data 
----------------------|----------------
Page Name |/Menu.php
Screen Size |900x1440
Window Size |751x1440
Page Size |1479x1440
Platform Information | Linux chaise.o2switch.net 3.10.0-714.10.2.lve1.5.17.1.el7.x86_64 #1 SMP Tue May 22 10:39:25 EDT 2018 x86_64
PHP Version | 7.2.19
SQL Version | 10.3.15-MariaDB
EcclesiaCRM Version |5.8.1
Reporting Browser |Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36
Prerequisite Status |All Prerequisites met
Integrity check status |{"status":"success"}
Apache Modules    |mod_rewrite,mod_mime,mod_headers,mod_expires,mod_auth_basic

**Comment by phili67** [comment]
Qu'est ce qui disparait de manière aléatoire  ?????
