### ISSUE TITLE
Bug  - bp les participants

### ISSUE THREAD

**Issue by EcclesiaCRMBugReport** [phili67/ecclesiacrm#138]
message d'erreur suivant lorsque l'on clic sur bouton les participants 

DataTables warning: table id=eventsTable - Requested unknown parameter '1' for row 0. For more information about this error, please see http://datatables.net/tn/4

Collected Value Title |  Data 
----------------------|----------------
Page Name |/ListEvents.php
Screen Size |900x1440
Window Size |792x1264
Page Size |792x1264
Platform Information | Linux tournevis.o2switch.net 3.10.0-714.10.2.lve1.4.79.el6h.x86_64 #1 SMP Thu Jan 4 14:26:00 EST 2018 x86_64
PHP Version | 7.0.27
SQL Version | 10.0.33-MariaDB
EcclesiaCRM Version |3.2.0
Reporting Browser |Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/604.4.7 (KHTML, like Gecko) Version/11.0.2 Safari/604.4.7
Prerequisite Status |All Prerequisites met
Integrity check status |{"status":"success"}
Apache Modules    |mod_rewrite,mod_mime,mod_headers,mod_expires,mod_auth_basic

**Comment by phili67** [comment]
Le bug est corrigé.
Tu peux le voir sur le site démo.
