### ISSUE TITLE
DB upgrade issue

### ISSUE THREAD

**Issue by pagaremos** [phili67/ecclesiacrm#140]
Must DB be upgraded all the time?

When I load EcclesiaCRM initially with the sample database I always get the notice below and after few seconds it's done.

Upgrade Required
Current DB Version: 2.10.0 
Current Software Version: 3

But version 3.1.0 never upgrades. See the attached image.

![upgrade issue](https://user-images.githubusercontent.com/6854741/35245698-00fea328-ff79-11e7-9309-2f009eae1a9e.jpg)
.1.0

**Comment by phili67** [comment]
Ok I found a solution.

The 3.0 can upgrade the 2.10.x which were real experimental versions.
You can download the version here : https://github.com/phili67/ecclesiacrm/releases/tag/3.0.0

You unzip the files in your folder where ChurchCRM is here.
Last you change the rights to with : chown -R  www-data:www-data your_folder.

After it's easy to upgrade to the 3.1 version and after.

**Comment by pagaremos** [comment]
Well, I just created new data entries. Its ok. Thanks
