### ISSUE TITLE
Error after installation.

### ISSUE THREAD

**Issue by Nene-efo** [phili67/ecclesiacrm#1787]
**If you have the EcclesiaCRM software running, please file an issue using the _Report an issue_ in the help menu.**

After completing the installation forms, I get the following messages instead of the login page.

**Fatal error: Uncaught Error: Call to a member function getVersion() on null in C:\Program Files\Ampps\www\ecclesiacrm\EcclesiaCRM\Service\SystemService.php:87 Stack trace: #0 C:\Program Files\Ampps\www\ecclesiacrm\EcclesiaCRM\Bootstrapper.php(332): EcclesiaCRM\Service\SystemService::getDBVersion() #1 C:\Program Files\Ampps\www\ecclesiacrm\EcclesiaCRM\Bootstrapper.php(82): EcclesiaCRM\Bootstrapper::isDBCurrent() #2 C:\Program Files\Ampps\www\ecclesiacrm\Include\LoadConfigs.php(33): EcclesiaCRM\Bootstrapper::init('127.0.0.1', '3306', 'root', 'mysql', 'ecc7', '/ecclesiacrm', false, Array, false) #3 C:\Program Files\Ampps\www\ecclesiacrm\Include\Config.php(62): require_once('C:\\Program File...') #4 C:\Program Files\Ampps\www\ecclesiacrm\index.php(7): require_once('C:\\Program File...') #5 {main} thrown in C:\Program Files\Ampps\www\ecclesiacrm\EcclesiaCRM\Service\SystemService.php on line 87**

**Comment by phili67** [comment]
OK I've never test EcclesiaCRM on Ampps (with Windows).

Did you use Apache on our installation.

I think you you have to install the mod_rewrite module.

I use url rewriting features of this module to define the routes like for example :
https//ip_of_your_server/v2/dashboard

Hopefully this help you,

Philippe
