### ISSUE TITLE
Pledge Summary

### ISSUE THREAD

**Issue by pagaremos** [phili67/ecclesiacrm#227]
I get this error when running a report of pledges:

"Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; PDF_PledgeSummaryReport has a deprecated constructor in C:\wamp64\www\Reports\PledgeSummary.php on line 92

Fatal error: Uncaught Exception: FPDF error: Some data has already been output, can't send PDF file in C:\wamp64\www\vendor\setasign\fpdf\fpdf.php:271 Stack trace: #0 C:\wamp64\www\vendor\setasign\fpdf\fpdf.php(1063): FPDF->Error('Some data has a...') #1 C:\wamp64\www\vendor\setasign\fpdf\fpdf.php(1012): FPDF->_checkoutput() #2 C:\wamp64\www\Reports\PledgeSummary.php(268): FPDF->Output('D', 'PledgeSummaryRe...') #3 {main} thrown in C:\wamp64\www\vendor\setasign\fpdf\fpdf.php on line 271"

**Comment by phili67** [comment]
It's closed
