### ISSUE TITLE
Database first install issue

### ISSUE THREAD

**Issue by FakeShell** [phili67/ecclesiacrm#2278]
**If you have the EcclesiaCRM software running, please file an issue using the _Report an issue_ in the help menu.**

####  On what page in the application did you find this issue?
first setup

#### What browser (and version) are you running?
Chromium
#### What version of PHP is the server running?
8.0

#### What version of SQL Server are you running?
Mariadb 10.1
#### What version of EcclesiaCRM are you running?
Latest

Database is created and running on the server and local login works. but when doing the first startup it fails with "connection to database failed"
Tried with multiple users both with user being accessible remotely and locally none of them worked. does ecclesia save any logs anywhere?

**Comment by phili67** [comment]
Hello,
you have logs in the logs folder.

Otherwise you have to go to /var/log/...

Be careful to check that the prerequisites are present:
https://www.docs.ecclesiacrm.com/en/user-guide/doc-installation/doc-requirement/

Tell me what is the log return at Ecclesia level.

**Comment by FakeShell** [comment]
missing php extensions
got it working
thanks
