### ISSUE TITLE
TypeError: Failed to execute 'createObjectURL' on 'URL': Overload resolution failed.

### ISSUE THREAD

**Issue by technomango** [phili67/ecclesiacrm#2475]
**If you have the EcclesiaCRM software running, please file an issue using the _Report an issue_ in the help menu.**

#### What version of EcclesiaCRM are you running?

I am running Linux Centos
EcclesiaCRM 7.6.0
PHP 8.0

I am getting this error when I try to take a picture at User Profile

I recorded the screnn so you can see it clearly

Thanks

https://github.com/phili67/ecclesiacrm/assets/5431518/286060dd-83fa-4be6-adf9-571cf3c4be48

**Comment by phili67** [comment]
We're not supporting any fork of EcclesiaCRM.

Best to you
