### ISSUE TITLE
Save Error

### ISSUE THREAD

**Issue by pagaremos** [phili67/ecclesiacrm#287]
Hello Phili,

I was testing EcclesiaCRM version 3.6.2 and there are errors with saving a person data. Looks like a connection string issue. See the image attatched:
![save error](https://user-images.githubusercontent.com/6854741/39662760-e70855f4-505e-11e8-9ca8-f80a47544acf.jpg)

**Comment by phili67** [comment]
I can't reproduce the problem, you've mentioned.
Could you give me a way to reproduce the same issue?

**Comment by phili67** [comment]
closes. This was a bug from a bad installation
