### ISSUE TITLE
Erreur installation manque dossier vendor

### ISSUE THREAD

**Issue by SylvainFelden** [phili67/ecclesiacrm#38]
**Lors de l'installation de l'application erreur  ** 

[Wed Jan 03 14:38:01.065072 2018] [php7:error] [pid 63995] [client 127.0.0.1:54122] PHP Fatal error:  require_once(): Failed opening required '/Library/WebServer/Documents/ecclesia/ecclesiacrm/src/setup/../vendor/autoload.php' (include_path='.:') in /Library/WebServer/Documents/ecclesia/ecclesiacrm/src/setup/index.php on line 13

**Code concerné :**

if (file_exists('../Include/Config.php')) {
    header('Location: ../index.php');
} else {
    require_once dirname(__FILE__) . '/../vendor/autoload.php';

**Le dossier vendor n'existe pas**

**Comment by phili67** [comment]
Le problème devrait être réglé pour ton env de dev.
