### ISSUE TITLE
Duplicate Report

### ISSUE THREAD

**Issue by EcclesiaCRMBugReport** [phili67/ecclesiacrm#549]
Hi,

In the reports menu there are 2 identical reports and only one works. Report is called Family Member Count.

I think its the first one that does not work.

Thanks

Rohan

Collected Value Title |  Data 
----------------------|----------------
Page Name |/members2/IntegrityCheck.php
Screen Size |900x1440
Window Size |763x1385
Page Size |1830x1385
Platform Information | Linux server102.web-hosting.com 2.6.32-896.16.1.lve1.4.49.el6.x86_64 #1 SMP Fri Jan 5 05:15:23 EST 2018 x86_64
PHP Version | 7.0.31
SQL Version | 10.1.31-MariaDB-cll-lve
EcclesiaCRM Version |4.5.1
Reporting Browser |Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36 OPR/54.0.2952.60
Prerequisite Status |All Prerequisites met
Integrity check status |{"status":"failure","message":"One or more files failed signature validation","files":[{"filename":"vendor\/authorizenet\/authorizenet\/lib\/net\/authorize\/api\/contract\/v1\/CreditCardMaskedType.php","status":"Hash Mismatch","expectedhash":"df5a88b58917c9f7ac7c959087870d08e7478199","actualhash":"aff98eaa2bdf0dcb0b2315bfad2812ac7702f03f"},{"filename":"vendor\/authorizenet\/authorizenet\/lib\/net\/authorize\/api\/contract\/v1\/GetCustomerPaymentProfileRequest.php","status":"Hash Mismatch","expectedhash":"6d213b3771b701cdf087b8e23e4feca3fd270cc4","actualhash":"efe3ab196cbeea55dfa80ea2ab4d7c87f5c9a6b1"},{"filename":"vendor\/authorizenet\/authorizenet\/lib\/net\/authorize\/api\/contract\/v1\/GetCustomerProfileRequest.php","status":"Hash Mismatch","expectedhash":"c9903c242748a4e29d097475f70d468754dad7ff","actualhash":"8302741ffdae2e86425e5357ad26c21b12fd880c"},{"filename":"vendor\/authorizenet\/authorizenet\/lib\/net\/authorize\/api\/contract\/v1\/GetMerchantDetailsResponse.php","status":"Hash Mismatch","expectedhash":"e07974fc8b3ace97dfc4885705af3d8216cf3df1","actualhash":"9aa1070b80268097676b1de29f193d50c4a8c2f3"},{"filename":"vendor\/authorizenet\/authorizenet\/lib\/net\/authorize\/api\/contract\/v1\/GetTransactionListForCustomerRequest.php","status":"Hash Mismatch","expectedhash":"237b56f89e18f87755bb814d2a843ecf15475db3","actualhash":"9dca93919f5ff85a5bd357f0c481412c937b7844"},{"filename":"vendor\/authorizenet\/authorizenet\/lib\/net\/authorize\/api\/contract\/v1\/MerchantAuthenticationType.php","status":"Hash Mismatch","expectedhash":"7caa967eb421c0c97d2e72d513841db1ae233c5a","actualhash":"d4e779c078930a93d972a49a489eb23804b35bb8"},{"filename":"vendor\/authorizenet\/authorizenet\/lib\/net\/authorize\/api\/contract\/v1\/ProcessorType.php","status":"Hash Mismatch","expectedhash":"481fdce4c2f9a2da5147613170b1d7ec87fa5578","actualhash":"b54f996d6803cc283419c1fb396e320748c2b4f4"},{"filename":"vendor\/authorizenet\/authorizenet\/lib\/net\/authorize\/api\/contract\/v1\/SecurePaymentContainerErrorType.php","status":"Hash Mismatch","expectedhash":"81a8c6de2d4329647927900b6a85259bd0e17b94","actualhash":"a9301ee27e3a6d1fa76fd38549aa882017022bb5"},{"filename":"vendor\/authorizenet\/authorizenet\/lib\/net\/authorize\/api\/contract\/v1\/SecurePaymentContainerRequest.php","status":"Hash Mismatch","expectedhash":"a37819c373c6f08d509c301e93da3e6673dbcf0a","actualhash":"5df91d1904d0774abffece37884e7e33ad664bd3"},{"filename":"vendor\/authorizenet\/authorizenet\/lib\/net\/authorize\/api\/contract\/v1\/SecurePaymentContainerResponse.php","status":"Hash Mismatch","expectedhash":"24caa61866a3b4e8c028acdf9fe820bcb0b312a0","actualhash":"30dbff9c75373659c06007df6feeb1f08c3da680"},{"filename":"vendor\/authorizenet\/authorizenet\/lib\/net\/authorize\/api\/contract\/v1\/SubMerchantType.php","status":"Hash Mismatch","expectedhash":"c8e37ab61d4660ce8a4facaeb5599711087f71ae","actualhash":"b493bff0ed3b0be046c6cda61770f0438720756d"},{"filename":"vendor\/authorizenet\/authorizenet\/lib\/net\/authorize\/api\/contract\/v1\/TransactionDetailsType.php","status":"Hash Mismatch","expectedhash":"ec9e40c2d37cc15a45eb3d85e0aefeed42f4a946","actualhash":"3b01cc96e53baf707f71cf66f2058a967ce859cc"},{"filename":"vendor\/authorizenet\/authorizenet\/lib\/net\/authorize\/api\/contract\/v1\/TransactionRequestType.php","status":"Hash Mismatch","expectedhash":"c9b0f89f124c9dda89893de686eb62db4ecc368f","actualhash":"a7a694fcac1004124c12419256412e43b69abf0c"},{"filename":"vendor\/authorizenet\/authorizenet\/lib\/net\/authorize\/api\/contract\/v1\/TransactionResponseType.php","status":"Hash Mismatch","expectedhash":"b0ad102ed5c6024a65f5414d9f67f4e2e4dc4ed2","actualhash":"7322d9f37515cdbc74e62db6cf7ac0eb741ca2ae"},{"filename":"vendor\/authorizenet\/authorizenet\/lib\/net\/authorize\/api\/contract\/v1\/TransactionSummaryType.php","status":"Hash Mismatch","expectedhash":"878baf0b7b0dc75d4b86f088aec38d96247c46c5","actualhash":"fb184ea1224c93ca0d08181e0a8b32de4e33758b"},{"filename":"vendor\/authorizenet\/authorizenet\/lib\/net\/authorize\/api\/contract\/v1\/TransRetailInfoType.php","status":"Hash Mismatch","expectedhash":"b84649792bda1f3dffef28f8f7357479ef781854","actualhash":"2a33e4f6ee10de0cf96347573564b3773ca725d7"},{"filename":"vendor\/authorizenet\/authorizenet\/lib\/net\/authorize\/api\/contract\/v1\/WebCheckOutDataType.php","status":"Hash Mismatch","expectedhash":"a821fc570ac92394edbc31154e491e124363725a","actualhash":"92e444e4a5cdc9b30fb58311c38f854a6cd8f713"},{"filename":"vendor\/authorizenet\/authorizenet\/lib\/net\/authorize\/api\/contract\/v1\/WebCheckOutDataType\/TokenAType.php","status":"Hash Mismatch","expectedhash":"c256b2bdc75e7698ba93344fbabc885ee31b4724","actualhash":"eb8f85f50d147283800a6bc3ea092e42676cd968"},{"filename":"skin\/external\/ckeditor\/plugins\/codesnippet\/lib\/highlight\/highlight.pack.js","status":"Hash Mismatch","expectedhash":"01a6688d156cf14f08512e0daf0fb4da04c2aaf7","actualhash":"43a24282a3160985f266e3c5fed57a7ef6fb76fd"},{"filename":"skin\/external\/ckeditor\/styles.js","status":"Hash Mismatch","expectedhash":"92aef2d89c727b9c3bf5d1374e21850837f2607c","actualhash":"f408a685b9a02b78c8c6ee434a354d78c7a58a4c"},{"filename":"skin\/external\/fullcalendar\/fullcalendar.js","status":"Hash Mismatch","expectedhash":"013750b616edf17a0edc7c743042df3bd54b4450","actualhash":"7500162b0ebe66d591ff90ca184a3248c17df631"},{"filename":"skin\/external\/leaflet\/leaflet-src.js","status":"Hash Mismatch","expectedhash":"a497fcef58f8ccdcb631b4deb9ded3e4a92c0259","actualhash":"2dc3e3f7435024d9a8f4da6ea0a1bb6f991b3805"},{"filename":"skin\/fullcalendar\/fullcalendar.js","status":"Hash Mismatch","expectedhash":"013750b616edf17a0edc7c743042df3bd54b4450","actualhash":"7500162b0ebe66d591ff90ca184a3248c17df631"}]}
Apache Modules    |mod_rewrite,mod_mime,mod_headers,mod_expires,mod_auth_basic

**Comment by phili67** [comment]
Ok the problem is now solved.
