### ISSUE TITLE
Labels incorrect for Family Form

### ISSUE THREAD

**Issue by EcclesiaCRMBugReport** [phili67/ecclesiacrm#579]
Hi,

When editing a family record there are 2 incorrect labels.

I think they are County and Postcode.

It is showing as e and y?

Please look into this.

Thanks

Rohan

Collected Value Title |  Data 
----------------------|----------------
Page Name |/membership/FamilyEditor.php
Screen Size |768x1366
Window Size |662x1349
Page Size |1541x1349
Platform Information | Linux server102.web-hosting.com 2.6.32-896.16.1.lve1.4.49.el6.x86_64 #1 SMP Fri Jan 5 05:15:23 EST 2018 x86_64
PHP Version | 7.0.31
SQL Version | 10.1.31-MariaDB-cll-lve
EcclesiaCRM Version |4.5.2
Reporting Browser |Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36
Prerequisite Status |All Prerequisites met
Integrity check status |{"status":"success"}
Apache Modules    |mod_rewrite,mod_mime,mod_headers,mod_expires,mod_auth_basic

**Comment by phili67** [comment]
I can't reproduce the problem, could you send a screenshot ?

**Comment by rohanale** [comment]
![image](https://user-images.githubusercontent.com/6361599/45089410-fd732480-b103-11e8-957a-69faead1858e.png)

**Comment by phili67** [comment]
I've tried to fix this through #592

**Comment by phili67** [comment]
4.8.0 closed the issue
