### ISSUE TITLE
Directory Reports Error

### ISSUE THREAD

**Issue by EcclesiaCRMBugReport** [phili67/ecclesiacrm#580]
Hi,
When printing a directory report it does not print the label for the Mobile phone properly.

See screenshot I will attach.

Thanks

Rohan

Collected Value Title |  Data 
----------------------|----------------
Page Name |/membership/DirectoryReports.php
Screen Size |1200x1920
Window Size |1035x1903
Page Size |1833x1903
Platform Information | Linux server102.web-hosting.com 2.6.32-896.16.1.lve1.4.49.el6.x86_64 #1 SMP Fri Jan 5 05:15:23 EST 2018 x86_64
PHP Version | 7.0.31
SQL Version | 10.1.31-MariaDB-cll-lve
EcclesiaCRM Version |4.5.2
Reporting Browser |Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:61.0) Gecko/20100101 Firefox/61.0
Prerequisite Status |All Prerequisites met
Integrity check status |{"status":"success"}
Apache Modules    |mod_rewrite,mod_mime,mod_headers,mod_expires,mod_auth_basic

**Comment by rohanale** [comment]
Attaching screenshot ...
![directoryerror](https://user-images.githubusercontent.com/6361599/44938757-93135a80-ad78-11e8-8069-ca9f8f8ba7e9.JPG)

**Comment by rohanale** [comment]
![capture](https://user-images.githubusercontent.com/6361599/44938797-c950da00-ad78-11e8-9fd2-94fdb83608b1.JPG)

**Comment by rohanale** [comment]
Just a bit more info on this issue.  The issue appears before you actually create the PDF.  See attached screenshot...

![persondirectoryerror](https://user-images.githubusercontent.com/6361599/45246512-a5057800-b2f9-11e8-8098-c6643646566d.JPG)

**Comment by phili67** [comment]
This is closed with 4.8.0
