### ISSUE TITLE
Incorrect Label

### ISSUE THREAD

**Issue by EcclesiaCRMBugReport** [phili67/ecclesiacrm#597]
Hi,

There is an incorrect label when adding a new family.

I believe the field is post code or zip code.

It is showing as just y.

See screenshot.

Thanks

Rohan

Collected Value Title |  Data 
----------------------|----------------
Page Name |/membership/FamilyEditor.php
Screen Size |900x1440
Window Size |794x1423
Page Size |1561x1423
Platform Information | Linux server102.web-hosting.com 2.6.32-896.16.1.lve1.4.49.el6.x86_64 #1 SMP Fri Jan 5 05:15:23 EST 2018 x86_64
PHP Version | 7.0.31
SQL Version | 10.1.35-MariaDB-cll-lve
EcclesiaCRM Version |4.6.1
Reporting Browser |Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36
Prerequisite Status |All Prerequisites met
Integrity check status |{"status":"success"}
Apache Modules    |mod_rewrite,mod_mime,mod_headers,mod_expires,mod_auth_basic

**Comment by rohanale** [comment]
![addnewfamily](https://user-images.githubusercontent.com/6361599/45246326-979bbe00-b2f8-11e8-8359-804ffe5b0b3f.JPG)

**Comment by rohanale** [comment]
![addnewfamily](https://user-images.githubusercontent.com/6361599/45246351-b5692300-b2f8-11e8-9a34-1590b4079fc8.JPG)

**Comment by phili67** [comment]
This is now closed with 4.8.0
