### ISSUE TITLE
Multiple Records Deleting

### ISSUE THREAD

**Issue by pagaremos** [phili67/ecclesiacrm#74]
Hi Phili, is it possible to allow for multiple person deletion?

**Comment by phili67** [comment]
Could you please explain more about this part ?

**Comment by pagaremos** [comment]
Precisely, if I want to delete 10 people from the system, there should be a checkbox for multiple selection. For now, we are only able to delete one at a time. So for example if we have 3 people dead, we can search for all dead members and delete their records.

I hope this will be clear. Let me know if you still need clarification.
