### ISSUE TITLE
malformed header from script 'index.php': Bad header: Access-Control-Allow-Origin

### ISSUE THREAD

**Issue by erwan3d** [phili67/ecclesiacrm#935]
Bonjour,

j'ai réussi à installer churchCRM sur le serveur mutualisé OVH, mais je n'arrive pas à installer ecclesiaCRM.
j'ai ce log qui ressort sur OVH:

[Tue Feb 05 18:47:33 2019] [error] [client 78.abc.ab.abc] [host ecclesiacrm.*****.fr] malformed header from script 'index.php': Bad header: Access-Control-Allow-Origin

j'ai tout mis en chmd 755

une idée?

Merci

Erwan C.

**Comment by phili67** [comment]
Il y a des .htaccess dans les deux CRM, l'installer par glisser déposer peut poser de réel problème.
Il est nécessaire de paramétrer finement cette partie.
Le contenu de ces .htaccess sont de la forme :
RewriteEngine On

# Some hosts may require you to use the `RewriteBase` directive.
# If you need to use the `RewriteBase` directive, it should be the
# absolute physical path to the directory that contains this htaccess file.
#
# RewriteBase /

RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^(.*)$ index.php [QSA,L]

Il y en a trois :
- un à la racine du site (la ou il y a index.php)
- un dans le dossier setup
- un dans le dossier api

Bien à vous

**Comment by phili67** [comment]
Je travaille finalement sur la solution : Access-Control-Allow-Origin

J'ai un work around qui posera un pb sur le contrôle d'intégrité du soft !!!
```
<?php

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

use EcclesiaCRM\dto\SystemURLs;
use EcclesiaCRM\dto\SystemConfig;

$csp = array(
    "default-src 'self'",
    "script-src 'self' 'unsafe-eval' 'nonce-".SystemURLs::getCSPNonce()."' sidecar.gitter.im browser-update.org maps.googleapis.com www.bing.com  dev.virtualearth.net t.ssl.ak.dynamic.tiles.virtualearth.net cdnjs.cloudflare.com", /*'nonce-".SystemURLs::getCSPNonce()."' // replacement of : 'unsafe-inline' */
    "object-src 'none'",
    "style-src 'self' 'unsafe-inline' fonts.googleapis.com www.bing.com",
    "img-src 'self' www.google.com d maps.gstatic.com maps.googleapis.com a.tile.openstreetmap.org b.tile.openstreetmap.org c.tile.openstreetmap.org www.bing.com t.ssl.ak.dynamic.tiles.virtualearth.net data:",
    "media-src 'self'",
    "frame-src 'self' www.youtube.com",
    "font-src 'self' fonts.gstatic.com",
    "connect-src 'self' www.bing.com  nominatim.openstreetmap.org",
    "report-uri ".SystemURLs::getRootPath()."/api/system/csp-report"
);
if (SystemConfig::getBooleanValue("bHSTSEnable")) {
    header('Strict-Transport-Security: max-age=31536000; includeSubDomains');
}
header('X-Frame-Options: SAMEORIGIN');
header("Content-Security-Policy-Report-Only:".join(";", $csp));
header("Access-Control-Allow-Origin", "*");
```

**Comment by phili67** [comment]
J'ai juste pushé un nouvelle version qui devrait en théorie résoudre votre problème.

**Comment by erwan3d** [comment]
super, merci, je teste ca!!

**Comment by phili67** [comment]
Alors cela donne quoi ?
