### ISSUE TITLE
DB Error

### ISSUE THREAD

**Issue by pagaremos** [phili67/ecclesiacrm#97]
Page in the application with issue: http://localhost/EventNames.php

Type of server running: Localhost Windows.

Browser (and version): Google Chrome, latest

Version of PHP the server running: 7.19

Version of SQL Server: 5.7.19 

EcclesiaCRM version: 3.0.0
![db error](https://user-images.githubusercontent.com/6854741/34752347-ab59a130-f5a9-11e7-9c22-fd48b0eb45e1.jpg)

Hi Phili, I get the above error when I try to create a new event.

Please help

**Comment by phili67** [comment]
The problem is normally solved in the new version.
