### ISSUE TITLE
Feature Request. 

### ISSUE THREAD

**Issue by pagaremos** [phili67/ecclesiacrm#98]
Phili67 you can add church branches. For example if there are 3 churches in Paris, we can select the branch and see its members or people. 

Or if there are 4 churches in Marseille we can choose a branch in Marseille and see its members. What will happen is that, the church admin can be given the chance to create branches during initial installation of EcclesiaCRM.

So he creates all his branches and add members to it. Then in EcclesiaCRM menu we can select a branch to see its members.

This feature is not in ChurchCRM. We can think of this. I know you are full of surprises. 👍

**Comment by phili67** [comment]
This is a massive changement of the CRM and it's enormous :
- security problem from one church to another.
- the user must be in a group of user
- the event too
- the group ....
- everything the settings ....
I think
