### ISSUE TITLE
Traduction manquante

### ISSUE THREAD

**Issue by EcclesiaCRMBugReport** [phili67/ecclesiacrm#99]
Dans l'écran famille 
Les rôles des membres et la classification ne sont pas traduit en français.

Collected Value Title |  Data 
----------------------|----------------
Page Name |/FamilyEditor.php
Screen Size |900x1440
Window Size |769x1440
Page Size |1692x1440
Platform Information | Linux tournevis.o2switch.net 3.10.0-714.10.2.lve1.4.79.el6h.x86_64 #1 SMP Thu Jan 4 14:26:00 EST 2018 x86_64
PHP Version | 7.0.26
SQL Version | 10.0.33-MariaDB
EcclesiaCRM Version |3.0.0
Reporting Browser |Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/604.4.7 (KHTML, like Gecko) Version/11.0.2 Safari/604.4.7
Prerequisite Status |All Prerequisites met
Integrity check status |{"status":"success"}
Apache Modules    |mod_rewrite,mod_mime,mod_headers,mod_expires,mod_auth_basic

**Comment by phili67** [comment]
Cela peut être fait dans la configuration :
![capture d ecran 2018-01-10 a 23 06 48](https://user-images.githubusercontent.com/20263693/34814526-4a2dbf4e-f6ae-11e7-8ed7-402cbdbe38b4.png)

On peut ensuite mettre ce que l'on veut :
![capture d ecran 2018-01-10 a 23 06 40](https://user-images.githubusercontent.com/20263693/34814536-50e588bc-f6ae-11e7-825a-1be0958ce97d.png)

Puis on a cela :
![capture d ecran 2018-01-10 a 23 07 11](https://user-images.githubusercontent.com/20263693/34814547-5c2f79f8-f6ae-11e7-85c5-b48f90a6eea3.png)
